name: CMake CI

on: [push]

jobs:
    build-library:
        runs-on: ubuntu-latest
        - uses: actions/checkout@v2
        - name: Setup CMake
          uses: jwlawson/actions-setup-cmake@v1.4
          with:
            cmake-version: '3.18.x'
        - name: Use CMake
          run: cmake --version
        - name: Get Ninja
          uses: seanmiddleditch/gha-setup-ninja@master
        - name: Setup Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.9.0' # Version range or exact version of a Python version to use, using SemVer's version range syntax
            architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
        - name: Get Python version and Pip
          run: |
            python --version
            python -m pip install --upgrade pip
            pip --version
        - name: Get Conan
          run: |
            pip install conan
            conan --version
        - name: Build Debug library
          run: python3 scripts/run.py crypto_debug
        - name: Build Release library
          run: python3 scripts/run.py crypto_release
